Remove unused oslo-config-generator parts
These were added in d3e074ff5e5efeb0451690943b97dfa43a71237d but we do
not use them to configure drivers (this is done in neutron
configuration), and do not work:
$ oslo-config-generator --namespace flow_classifier
Traceback (most recent call last):
[...]
ImportError: No module named opts

Change-Id: Ibd11055425c269e8f11990ddf978e177cdc2f035